service: serverless-typescript-demo

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-offline

functions:
  hello:
    handler: dist/handler.handle

    events:
     - http:
         path: hello
         method: get
